import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type LanguageCode = 'he' | 'en' | 'ar' | 'es' | 'fr' | 'de' | 'ru' | 'pt' | 'it' | 'zh' | 'ja' | 'ko';

interface Language {
  code: LanguageCode;
  native: string;
  english: string;
}

const languages: Language[] = [
  { code: 'he', native: 'עברית', english: 'Hebrew' },
  { code: 'en', native: 'English', english: 'English' },
  { code: 'ar', native: 'العربية', english: 'Arabic' },
  { code: 'es', native: 'Español', english: 'Spanish' },
  { code: 'fr', native: 'Français', english: 'French' },
  { code: 'de', native: 'Deutsch', english: 'German' },
  { code: 'ru', native: 'Русский', english: 'Russian' },
  { code: 'pt', native: 'Português', english: 'Portuguese' },
  { code: 'it', native: 'Italiano', english: 'Italian' },
  { code: 'zh', native: '中文', english: 'Chinese' },
  { code: 'ja', native: '日本語', english: 'Japanese' },
  { code: 'ko', native: '한국어', english: 'Korean' },
];

type TranslationMap = Record<string, string>;
type TranslationsDict = Record<LanguageCode, TranslationMap>;

const translations: TranslationsDict = {
  he: {
    'app.title': 'שופט וירטואלי',
    'app.titleEn': 'Virtual Referee',
    'chat.thinking': 'השופט הווירטואלי חושב...',
    'chat.placeholder': 'שאל שאלה על חוקי FLL...',
    'chat.send': 'שלח',
    'chat.greeting': 'שלום! אני השופט הווירטואלי. אני מכיר את חוקי עונת {season}. איך אני יכול לעזור?',
    'chat.fileReceived': 'קובץ חוקים חדש ({name}) התקבל. זוהתה עונת {season}. שומר בענן...',
    'chat.fileLearned': 'למדתי את העדכונים מקובץ החוקים! המידע נשמר בענן ומוכן לשימוש מכל מכשיר.',
    'chat.uploadError': 'שגיאה בהעלאת הקובץ: ',
    'chat.systemHint': '(הנחיה לשופט: אם השאלה עוסקת במשימה חדשה או מצב חדש - התעלם מהמשימה שנדונה קודם לכן ואל תערבב בין חוקים או ניקודים של משימות שונות.)',
    'chat.commError': 'שגיאת תקשורת. אנא נסה שוב.',
    'chat.connectionLost': 'אבד הקשר. נסה שוב מאוחר יותר.',
    'chat.suggestion1': 'האם מותר לרובוט להתרחב?',
    'chat.suggestion2': 'מה הניקוד למשימה 1?',
    'chat.suggestion3': 'מה העונש על נגיעה ברובוט?',
    'chat.suggestion4': 'חוקי אזור השיגור',
    'chat.refereeTag': '📋 שופט וירטואלי',
    'chat.foulTag': '🚨 כרטיס שופט וירטואלי',
    'chat.copied': 'התשובה הועתקה ללוח!',
    'chat.copy': 'העתק',
    'chat.thinking2': 'חושב...',
    'chat.researching': 'השופט חוקר...',
    'chat.placeholder2': 'שאל את השופט...',
    'chat.updating': 'מעדכן...',
    'chat.tip1': '📋 **הנחיית שופט וירטואלי:** רוח ספורטיבית (Gracious Professionalism) קודמת לכל הישג! כבדו את חבריכם ואת קבוצות היריב.',
    'chat.tip2': '⏱️ **חוקי הזירה:** ברגע שהגעתם לשולחן, יש לכם בדיוק 2:30 דקות להפעיל את כל המשימות שתרגלתם. בהצלחה!',
    'chat.tip3': '⚙️ **טיפ מקצועי:** זכרו, אם הרובוט יוצא מאזור הבית או משתבש במרכז המגרש - החזרתו לבית באקט ידני תגרור סימון עונש (דיסק משימה פנוי שעובר למשבצת העונשים).',
    'chat.tip4': '📏 **חוקי המבנה:** כל הציוד שלכם (כולל רובוט, אביזרים חלופיים וחלקי חילוף) חייב להיכנס במלואו לתחום אזור הבית או אזור השיגור קודם תחילת המקצה!',
    'chat.tip5': '🎯 **שימו לב:** השופט הווירטואלי מבוסס על בינה מלאכותית ומסתמך על ספר החוקים הרשמי. במקרה של ספק, מומלץ לפנות לשופט זירה אנושי.',
    'chat.whistle': '😗💨🎵 *שריקה חדה מהזירה!*',
    'admin.upload': 'העלה חוקים',
    'admin.uploadTitle': 'העלאת חוקים חדשים',
    'admin.uploadDesc': 'העלה קובץ טקסט או PDF עם החוקים החדשים. ה-AI ילמד אותם מיד.',
    'admin.uploadPick': 'לחץ לבחירת קובץ',
    'admin.uploading': 'מעלה ומעבד...',
    'admin.cancel': 'ביטול',
    'admin.corrections': 'תיקוני שופט',
    'admin.correctionsPlaceholder': 'תיקון אחד לכל שורה, למשל: משימה 05 - הניקוד הנכון הוא 25 נקודות כי...',
    'admin.saveCorrections': 'שמור תיקונים',
    'admin.saved': 'נשמר',
    'season.label': 'עונה:',
    'auth.logout': 'התנתק',
    'auth.login': 'התחברות',
    'auth.logoutConfirmTitle': 'התנתקות מהמערכת',
    'auth.logoutConfirmMsg': 'האם אתה בטוח שברצונך להתנתק מהמ system?',
    'auth.logoutConfirmYes': 'כן, התנתק',
    'auth.logoutConfirmNo': 'ביטול',
    'auth.loginTitle': 'התחברות',
    'auth.loginDesc': 'כדי להשתמש בבינה מלאכותית, אנא התחבר עם אימייל',
    'auth.loginWithEmail': 'התחברות עם אימייל',
    'auth.back': 'חזרה ↩',
    'intro.title': 'ברוך הבא לשופט הווירטואלי',
    'intro.desc': 'שופט FLL מבוסס בינה מלאכותית',
    'intro.subtitle': 'שופט זירה וירטואלי',
    'intro.descFull': 'שופט הזירה הווירטואלי הוא צ\'אט AI שנועד לעזור בהבנת חוקי המשחק.',
    'intro.feature1Title': 'שואלים במילים שלכם',
    'intro.feature1Desc': 'כל דבר שקשור למשחק הרובוט שואלים איך שרוצים ומקבלים תשובה ברורה.',
    'intro.feature2Title': 'זמין מכל מקום',
    'intro.feature2Desc': 'עובד מהטלפון, מהמחשב ומהזירה, תמיד זמין כשצריכים.',
    'intro.disclaimer': '⚠️ שימו לב:',
    'intro.disclaimerDesc': 'השופט הווירטואלי עלול לטעות. הפסיקה המחייבת היא תמיד של שופטי הזירה בתחרות הרשמית בלבד.',
    'intro.continue': 'המשך לשופט',
    'intro.continueLogin': 'המשך לכניסה',
    'intro.start': 'התחל שאילתה',
    'intro.badge': 'כלי קהילתי מבית Boeing 727 • לקהילת ה-FLL',
    'intro.feature3Title': 'מבוסס על המסמכים הרשמיים',
    'intro.feature3Desc': 'התשובות נשענות על החוקים והעדכונים הרשמיים של פירסט.',
    'intro.notOfficial': 'כלי קהילתי — אינו מוצר רשמי של FIRST',
    'disclaimerPopup.title': 'רגע לפני שנכנסים ⚠️',
    'disclaimerPopup.body': 'השופט הווירטואלי הוא רובוט חכם שעוזר לכם להבין את החוקים, אבל גם הוא יכול לטעות — כמו שכולנו לפעמים מתבלבלים.\n\nהוא לא קובע מה נכון בתחרות. בתחרות עצמה רק השופטים האמיתיים בזירה מחליטים, ומה שהם אומרים — זה מה שקובע, תמיד.\n\nאם יש לכם ספק, תמיד כדאי לשאול שופט אמיתי בזירה.',
    'disclaimerPopup.confirm': 'קראתי והבנתי — כניסה לשופט'
  },
  en: {
    'app.title': 'Virtual Referee',
    'app.titleEn': 'Virtual Referee',
    'chat.thinking': 'The virtual referee is thinking...',
    'chat.placeholder': 'Ask a question about FLL rules...',
    'chat.send': 'Send',
    'chat.greeting': 'Hello! I\'m the Virtual Referee. I know the rules of the {season} season. How can I help?',
    'chat.fileReceived': 'New rulebook file ({name}) received. Detected season: {season}. Saving to cloud...',
    'chat.fileLearned': 'I\'ve learned the updates from the rulebook file! The information is saved to the cloud and ready to use from any device.',
    'chat.uploadError': 'Error uploading file: ',
    'chat.systemHint': '(Judge instruction: If the question deals with a new mission or situation - ignore the previously discussed mission and don\'t mix rules or scoring from different missions.)',
    'chat.commError': 'Communication error. Please try again.',
    'chat.connectionLost': 'Connection lost. Try again later.',
    'chat.suggestion1': 'Can a robot expand?',
    'chat.suggestion2': 'What\'s the score for mission 1?',
    'chat.suggestion3': 'What\'s the penalty for touching the robot?',
    'chat.suggestion4': 'Launch zone rules',
    'chat.refereeTag': '📋 Virtual Referee',
    'chat.foulTag': '🚨 Referee Foul Card',
    'chat.copied': 'Answer copied to clipboard!',
    'chat.copy': 'Copy',
    'chat.thinking2': 'Thinking...',
    'chat.researching': 'The referee is researching...',
    'chat.placeholder2': 'Ask the referee...',
    'chat.updating': 'Updating...',
    'chat.tip1': '📋 **Virtual Referee Tip:** Gracious Professionalism comes before any achievement! Respect your fellow teams.',
    'chat.tip2': '⏱️ **Field Rules:** Once you reach the table, you have exactly 2:30 minutes to run all your practiced missions. Good luck!',
    'chat.tip3': '⚙️ **Professional Tip:** Remember, if the robot leaves the home area or malfunctions in the center of the field - retrieving it manually will result in a penalty (free mission disc moves to penalty slots).',
    'chat.tip4': '📏 **Structure Rules:** All your equipment (including robot, alternative accessories and spare parts) must fully fit within the home area or launch area before the match begins!',
    'chat.tip5': '🎯 **Important:** The Virtual Referee is based on AI and relies on the official rulebook. In case of doubt, it\'s recommended to consult a human field referee.',
    'chat.whistle': '😗💨🎵 *Sharp whistle from the field!*',
    'admin.upload': 'Upload Rules',
    'admin.uploadTitle': 'Upload New Rules',
    'admin.uploadDesc': 'Upload a text or PDF file with the new rules. The AI will learn them immediately.',
    'admin.uploadPick': 'Click to select file',
    'admin.uploading': 'Uploading and processing...',
    'admin.cancel': 'Cancel',
    'admin.corrections': 'Referee Corrections',
    'admin.correctionsPlaceholder': 'One correction per line, e.g.: Mission 05 - the correct score is 25 points because...',
    'admin.saveCorrections': 'Save Corrections',
    'admin.saved': 'Saved',
    'season.label': 'Season:',
    'auth.logout': 'Logout',
    'auth.login': 'Login',
    'auth.logoutConfirmTitle': 'Logout',
    'auth.logoutConfirmMsg': 'Are you sure you want to logout?',
    'auth.logoutConfirmYes': 'Yes, logout',
    'auth.logoutConfirmNo': 'Cancel',
    'auth.loginTitle': 'Login',
    'auth.loginDesc': 'To use the AI, please sign in with email',
    'auth.loginWithEmail': 'Sign in with Email',
    'auth.back': 'Back ↩',
    'intro.title': 'Welcome to the Virtual Referee',
    'intro.desc': 'AI-powered FLL Referee',
    'intro.subtitle': 'Virtual Field Referee',
    'intro.descFull': 'Ask any question about the game rules — get an instant answer with the exact rulebook section and a reference to official updates. A community tool built voluntarily by team Boeing 727 for the FLL community — not an official FIRST product.',
    'intro.feature1Title': 'Game Rules Inquiry',
    'intro.feature1Desc': 'Instant answer with the exact rulebook section — no guessing.',
    'intro.feature2Title': 'Scoring Explained',
    'intro.feature2Desc': 'How many points each mission is worth and the exact completion conditions.',
    'intro.disclaimer': '⚠️ Important:',
    'intro.disclaimerDesc': 'The Virtual Referee may make mistakes or miss certain details. As updates and improvements arrive, answers will become more accurate and reliable. This is part of the system\'s evolution. The rulings of the head referees and zone referees at the official competition are always decisive and final in every case. The bot\'s answers must not be considered an official binding approval during the competition.',
    'intro.continue': 'Continue to App',
    'intro.continueLogin': 'Continue to Login',
    'intro.start': 'Start Querying',
    'intro.badge': 'Community tool by Boeing 727 • For the FLL community',
    'intro.feature3Title': 'Referee Updates',
    'intro.feature3Desc': 'Clarifications, rulings and changes published throughout the season — in one place.',
    'intro.notOfficial': 'Community tool — not an official FIRST product',
    'disclaimerPopup.title': 'Heads up before you enter ⚠️',
    'disclaimerPopup.body': 'The Virtual Referee is a smart AI that tries to help you understand the rules, but it can make mistakes — just like we all sometimes get confused.\n\nIt does NOT decide what is correct in a competition. In the real competition, only the human field referees decide, and what they say is always final.\n\nIf in doubt, always ask a real field referee.',
    'disclaimerPopup.confirm': 'I read and understood — Enter Referee'
  },
  ar: {
    'app.title': 'الحكم الافتراضي',
    'app.titleEn': 'الحكم الافتراضي',
    'chat.thinking': 'الحكم الافتراضي يفكر...',
    'chat.placeholder': 'اسأل سؤالاً عن قوانين FLL...',
    'chat.send': 'إرسال',
    'chat.greeting': 'مرحباً! أنا الحكم الافتراضي. أعرف قوانين موسم {season}. كيف يمكنني مساعدتك؟',
    'chat.systemHint': '(تعليمات الحكم: إذا تناول السؤال مهمة جديدة أو وضعใหมاً - تجاهل المهمة التي نوقشت سابقاً ولا تخلط بين قوانين أو نقاط المهمات المختلفة.)',
    'chat.commError': 'خطأ في الاتصال. يرجى المحاولة مرة أخرى.',
    'chat.connectionLost': 'فُقد الاتصال. حاول مرة أخرى لاحقاً.',
    'chat.suggestion1': 'هل يجوز للروبوت أن يتوسع؟',
    'chat.suggestion2': 'ما هي نقاط المهمة 1؟',
    'chat.suggestion3': 'ما هي العقوبة على لمس الروبوت؟',
    'chat.suggestion4': 'قوانين منطقة الإطلاق',
    'chat.refereeTag': '📋 الحكم الافتراضي',
    'chat.foulTag': '🚨 بطاقة مخالفة من الحكم',
    'chat.copied': 'تم نسخ الإجابة!',
    'chat.copy': 'نسخ',
    'chat.thinking2': 'يفكر...',
    'chat.researching': 'الحكم يبحث...',
    'chat.placeholder2': 'اسأل الحكم...',
    'chat.updating': 'يُحدّث...',
    'admin.upload': 'رفع القوانين',
    'admin.uploadTitle': 'رفع قوانين جديدة',
    'admin.uploadDesc': 'ارفع ملف نصي أو PDF بالقوانين الجديدة. ستتعلمها الذكاء الاصطناعي فوراً.',
    'admin.uploadPick': 'اضغط لاختيار ملف',
    'admin.uploading': 'يرفع ومعالج...',
    'admin.cancel': 'إلغاء',
    'admin.corrections': 'تصحيحات الحكم',
    'admin.correctionsPlaceholder': 'تصحيح واحد في كل سطر، مثال: المهمة 05 - النقاط الصحيحة هي 25 نقطة لأن...',
    'admin.saveCorrections': 'حفظ التصحيحات',
    'admin.saved': 'تم الحفظ',
    'season.label': 'الموسم:',
    'auth.logout': 'تسجيل الخروج',
    'auth.login': 'تسجيل الدخول',
    'auth.logoutConfirmTitle': 'تسجيل الخروج',
    'auth.logoutConfirmMsg': 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
    'auth.logoutConfirmYes': 'نعم، سجل الخروج',
    'auth.logoutConfirmNo': 'إلغاء',
    'auth.loginTitle': 'تسجيل الدخول',
    'auth.loginDesc': 'لاستخدام الذكاء الاصطناعي، يرجى تسجيل الدخول بالبريد الإلكتروني',
    'auth.loginWithEmail': 'تسجيل الدخول بالبريد الإلكتروني',
    'auth.back': 'رجوع ↩',
    'intro.title': 'مرحبًا بك في الحكم الافتراضي',
    'intro.desc': 'حكم FLL بالذكاء الاصطناعي',
    'intro.subtitle': 'حكم ملعب افتراضي',
    'intro.descFull': 'اطرح أي سؤال عن قوانين اللعبة — واحصل على إجابة فورية مع الفقرة الدقيقة من كتاب القوانين وإحالة إلى التحديثات الرسمية. أداة مجتمعية بناها فريق Boeing 727 تطوعاً لمجتمع FLL — ليست منتجاً رسمياً من FIRST.',
    'intro.feature1Title': 'استفسار قواعد اللعبة',
    'intro.feature1Desc': 'إجابة فورية مع الفقرة الدقيقة من كتاب القوانين — دون تخمين.',
    'intro.feature2Title': 'شرح النقاط',
    'intro.feature2Desc': 'كم نقطة تستحق كل مهمة وما شروط إكمالها الدقيقة.',
    'intro.disclaimer': '⚠️ تنبيه:',
    'intro.disclaimerDesc': 'قد يخطئ الحكم الافتراضي أو يفوت بعض التفاصيل. مع وصول التحديثات والتحسينات، ستكون الإجابات أكثر دقة وموثوقية. هذا جزء من تطور النظام. قرارات الحكام الرئيسيين وحكام الحلبة في المسابقة الرسمية هي دائماً الحاسمة والنهائية في كل حالة. لا يجوز اعتبار إجابات البوت موافقة رسمية ملزمة أثناء المسابقة.',
    'intro.continue': 'المتابعة إلى التطبيق',
    'intro.continueLogin': 'المتابعة إلى تسجيل الدخول',
    'intro.start': 'ابدأ الاستعلام',
    'intro.badge': 'أداة مجتمعية من Boeing 727 • لمجتمع FLL',
    'intro.feature3Title': 'تحديثات التحكيم',
    'intro.feature3Desc': 'التوضيحات والقرارات والتغييرات المنشورة طوال الموسم — في مكان واحد.',
    'intro.notOfficial': 'أداة مجتمعية — ليست منتجاً رسمياً من FIRST',
    'disclaimerPopup.title': 'تنبيه قبل الدخول ⚠️',
    'disclaimerPopup.body': 'الحكم الافتراضي هو ذكاء اصطناعي ذكي يحاول مساعدتك، لكنه قد يخطئ — مثلنا جميعاً.\n\nهو لا يقرر ما هو صحيح في المسابقة. في المسابقة الحقيقية فقط الحكام البشريون في الملعب يقررون، وما يقولونه هو النهائي دائماً.\n\nإذا كان لديك شك، اسأل دائماً حكماً حقيقياً في الملعب.',
    'disclaimerPopup.confirm': 'قرأت وفهمت — دخول إلى الحكم'
  },
  es: {
    'app.title': 'Árbitro Virtual',
    'app.titleEn': 'Árbitro Virtual',
    'chat.thinking': 'El árbitro virtual está pensando...',
    'chat.placeholder': 'Haz una pregunta sobre las reglas de FLL...',
    'chat.send': 'Enviar',
    'chat.greeting': '¡Hola! Soy el Árbitro Virtual. Conozco las reglas de la temporada {season}. ¿Cómo puedo ayudarte?',
    'chat.systemHint': '(Instrucción del árbitro: Si la pregunta trata sobre una nueva misión o situación nueva, ignora la misión discutida anteriormente y no mezcles reglas o puntuación de diferentes misiones.)',
    'chat.commError': 'Error de comunicación. Por favor, inténtalo de nuevo.',
    'chat.connectionLost': 'Se perdió la conexión. Inténtalo más tarde.',
    'chat.suggestion1': '¿Puede un robot expandirse?',
    'chat.suggestion2': '¿Cuántos puntos vale la misión 1?',
    'chat.suggestion3': '¿Cuál es la penalización por tocar el robot?',
    'chat.suggestion4': 'Reglas de zona de lanzamiento',
    'chat.refereeTag': '📋 Árbitro Virtual',
    'chat.foulTag': '🚨 Tarjeta de Falta del Árbitro',
    'chat.copied': '¡Respuesta copiada al portapapeles!',
    'chat.copy': 'Copiar',
    'chat.thinking2': 'Pensando...',
    'chat.researching': 'El árbitro investiga...',
    'chat.placeholder2': 'Pregunta al árbitro...',
    'chat.updating': 'Actualizando...',
    'admin.upload': 'Subir reglas',
    'admin.uploadTitle': 'Subir nuevas reglas',
    'admin.uploadDesc': 'Sube un archivo de texto o PDF con las nuevas reglas. La IA las aprenderá de inmediato.',
    'admin.uploadPick': 'Haz clic para seleccionar archivo',
    'admin.uploading': 'Subiendo y procesando...',
    'admin.cancel': 'Cancelar',
    'admin.corrections': 'Correcciones del árbitro',
    'admin.correctionsPlaceholder': 'Una corrección por línea, ej.: Misión 05 - la puntuación correcta es 25 puntos porque...',
    'admin.saveCorrections': 'Guardar correcciones',
    'admin.saved': 'Guardado',
    'season.label': 'Temporada:',
    'auth.logout': 'Cerrar sesión',
    'auth.login': 'Iniciar sesión',
    'auth.logoutConfirmTitle': 'Cerrar sesión',
    'auth.logoutConfirmMsg': '¿Estás seguro de que deseas cerrar sesión?',
    'auth.logoutConfirmYes': 'Sí, cerrar sesión',
    'auth.logoutConfirmNo': 'Cancelar',
    'auth.loginTitle': 'Iniciar sesión',
    'auth.loginDesc': 'Para usar la IA, inicia sesión con correo electrónico',
    'auth.loginWithEmail': 'Iniciar sesión con Email',
    'auth.back': 'Volver ↩',
    'intro.title': 'Bienvenido al Árbitro Virtual',
    'intro.desc': 'Árbitro FLL con IA',
    'intro.subtitle': 'Árbitro de Campo Virtual',
    'intro.descFull': 'Haz cualquier pregunta sobre las reglas — obtén al instante la sección exacta del libro de reglas y la referencia a las actualizaciones oficiales. Herramienta comunitaria creada voluntariamente por el equipo Boeing 727 para la comunidad FLL — no es un producto oficial de FIRST.',
    'intro.feature1Title': 'Consulta de Reglas del Juego',
    'intro.feature1Desc': 'Respuesta instantánea con la sección exacta del libro de reglas — sin conjeturas.',
    'intro.feature2Title': 'Puntuación explicada',
    'intro.feature2Desc': 'Cuántos puntos vale cada misión y las condiciones exactas para completarla.',
    'intro.disclaimer': '⚠️ Importante:',
    'intro.disclaimerDesc': 'El Árbitro Virtual puede cometer errores o perder ciertos detalles. A medida que lleguen actualizaciones y mejoras, las respuestas serán más precisas y confiables. Esto es parte de la evolución del sistema. Las decisiones de los árbitros principales y de los árbitros de zona en la competición oficial son siempre decisivas y definitivas en cualquier caso. Las respuestas del bot no deben considerarse una aprobación oficial vinculante durante la competición.',
    'intro.continue': 'Continuar a la App',
    'intro.continueLogin': 'Continuar al Login',
    'intro.start': 'Comenzar consulta',
    'intro.badge': 'Herramienta comunitaria de Boeing 727 • Para la comunidad FLL',
    'intro.feature3Title': 'Actualizaciones del árbitro',
    'intro.feature3Desc': 'Aclaraciones, fallos y cambios publicados durante la temporada — en un solo lugar.',
    'intro.notOfficial': 'Herramienta comunitaria — no es un producto oficial de FIRST',
    'disclaimerPopup.title': 'Aviso antes de entrar ⚠️',
    'disclaimerPopup.body': 'El Árbitro Virtual es una IA inteligente que intenta ayudar, pero puede cometer errores — como todos nos confundimos a veces.\n\nNo decide qué es correcto en una competición. En la competición real solo los árbitros humanos de la zona deciden, y lo que dicen es siempre definitivo.\n\nSi tienes dudas, pregunta siempre a un árbitro real de la zona.',
    'disclaimerPopup.confirm': 'He leído y entendido — Entrar al Árbitro'
  },
  fr: {
    'app.title': 'Arbitre Virtuel',
    'app.titleEn': 'Arbitre Virtuel',
    'chat.thinking': 'L\'arbitre virtuel réfléchit...',
    'chat.placeholder': 'Posez une question sur les règles FLL...',
    'chat.send': 'Envoyer',
    'chat.greeting': 'Bonjour! Je suis l\'Arbitre Virtuel. Je connais les règles de la saison {season}. Comment puis-je vous aider?',
    'chat.systemHint': '(Instruction de l\'arbitre: Si la question concerne une nouvelle mission ou une nouvelle situation - ignorez la mission précédemment discutée et ne mélangez pas les règles ou les scores de différentes missions.)',
    'chat.commError': 'Erreur de communication. Veuillez réessayer.',
    'chat.connectionLost': 'Connexion perdue. Réessayez plus tard.',
    'chat.suggestion1': 'Un robot peut-il s\'étendre?',
    'chat.suggestion2': 'Quel est le score pour la mission 1?',
    'chat.suggestion3': 'Quelle est la pénalité pour toucher le robot?',
    'chat.suggestion4': 'Règles de la zone de lancement',
    'chat.refereeTag': '📋 Arbitre Virtuel',
    'chat.foulTag': '🚨 Carte de Faute de l\'Arbitre',
    'chat.copied': 'Réponse copiée!',
    'chat.copy': 'Copier',
    'chat.thinking2': 'Réflexion...',
    'chat.researching': 'L\'arbitre recherche...',
    'chat.placeholder2': 'Posez à l\'arbitre...',
    'chat.updating': 'Mise à jour...',
    'admin.upload': 'Télécharger les règles',
    'admin.uploadTitle': 'Télécharger de nouvelles règles',
    'admin.uploadDesc': 'Téléchargez un fichier texte ou PDF avec les nouvelles règles. L\'IA les apprendra immédiatement.',
    'admin.uploadPick': 'Cliquez pour sélectionner un fichier',
    'admin.uploading': 'Téléchargement et traitement...',
    'admin.cancel': 'Annuler',
    'admin.corrections': 'Corrections de l\'arbitre',
    'admin.correctionsPlaceholder': 'Une correction par ligne, ex. : Mission 05 - le score correct est de 25 points car...',
    'admin.saveCorrections': 'Enregistrer les corrections',
    'admin.saved': 'Enregistré',
    'season.label': 'Saison:',
    'auth.logout': 'Déconnexion',
    'auth.login': 'Connexion',
    'auth.logoutConfirmTitle': 'Déconnexion',
    'auth.logoutConfirmMsg': 'Êtes-vous sûr de vouloir vous déconnecter ?',
    'auth.logoutConfirmYes': 'Oui, déconnecter',
    'auth.logoutConfirmNo': 'Annuler',
    'auth.loginTitle': 'Connexion',
    'auth.loginDesc': 'Pour utiliser l\'IA, connectez-vous avec votre email',
    'auth.loginWithEmail': 'Se connecter avec Email',
    'auth.back': 'Retour ↩',
    'intro.title': 'Bienvenue à l\'Arbitre Virtuel',
    'intro.desc': 'Arbitre FLL par IA',
    'intro.subtitle': 'Arbitre de Terrain Virtuel',
    'intro.descFull': 'Posez toute question sur les règles — obtenez instantanément la section exacte du livre des règles et la référence aux mises à jour officielles. Outil communautaire créé bénévolement par l\'équipe Boeing 727 pour la communauté FLL — ce n\'est pas un produit officiel FIRST.',
    'intro.feature1Title': 'Enquête sur les Règles du Jeu',
    'intro.feature1Desc': 'Réponse instantanée avec la section exacte du livre des règles — sans supposition.',
    'intro.feature2Title': 'Score expliqué',
    'intro.feature2Desc': 'Combien de points vaut chaque mission et les conditions exactes de réussite.',
    'intro.disclaimer': '⚠️ Important:',
    'intro.disclaimerDesc': 'L\'Arbitre Virtuel peut commettre des erreurs ou manquer certains détails. À mesure que les mises à jour et les améliorations arrivent, les réponses deviendront plus précises et fiables. C\'est partie de l\'évolution du système. Les décisions des arbitres en chef et des arbitres de zone lors de la compétition officielle sont toujours décisives et définitives dans tous les cas. Les réponses du bot ne doivent pas être considérées comme une approbation officielle contraignante pendant la compétition.',
    'intro.continue': 'Continuer vers l\'App',
    'intro.continueLogin': 'Continuer vers la Connexion',
    'intro.start': 'Commencer',
    'intro.badge': 'Outil communautaire par Boeing 727 • Pour la communauté FLL',
    'intro.feature3Title': 'Mises à jour de l\'arbitre',
    'intro.feature3Desc': 'Clarifications, décisions et changements publiés pendant la saison — en un seul endroit.',
    'intro.notOfficial': 'Outil communautaire — pas un produit officiel FIRST',
    'disclaimerPopup.title': 'Attention avant d\'entrer ⚠️',
    'disclaimerPopup.body': 'L\'Arbitre Virtuel est une IA intelligente qui essaie d\'aider, mais elle peut se tromper — comme nous tous.\n\nElle ne décide pas de ce qui est correct en compétition. Lors de la vraie compétition, seuls les arbitres humains de l\'arène décident, et ce qu\'ils disent est toujours définitif.\n\nEn cas de doute, demandez toujours à un vrai arbitre de l\'arène.',
    'disclaimerPopup.confirm': 'J\'ai lu et compris — Entrer chez l\'Arbitre'
  },
  de: {
    'app.title': 'Virtueller Schiedsrichter',
    'app.titleEn': 'Virtueller Schiedsrichter',
    'chat.thinking': 'Der virtuelle Schiedsrichter denkt...',
    'chat.placeholder': 'Stelle eine Frage zu den FLL-Regeln...',
    'chat.send': 'Senden',
    'chat.greeting': 'Hallo! Ich bin der Virtuelle Schiedsrichter. Ich kenne die Regeln der {season}-Saison. Wie kann ich dir helfen?',
    'chat.systemHint': '(Schiedsrichter-Anweisung: Wenn die Frage eine neue Mission oder Situation betrifft - ignoriere die zuvor besprochene Mission und mische keine Regeln oder Punktzahlen verschiedener Missionen.)',
    'chat.commError': 'Kommunikationsfehler. Bitte versuche es erneut.',
    'chat.connectionLost': 'Verbindung verloren. Versuche es später erneut.',
    'chat.suggestion1': 'Darf sich ein Roboter ausdehnen?',
    'chat.suggestion2': 'Wie viele Punkte gibt es für Mission 1?',
    'chat.suggestion3': 'Was ist die Strafe für das Berühren des Roboters?',
    'chat.suggestion4': 'Startzonen-Regeln',
    'chat.refereeTag': '📋 Virtueller Schiedsrichter',
    'chat.foulTag': '🚨 Schiedsrichter-Foulkarte',
    'chat.copied': 'Antwort kopiert!',
    'chat.copy': 'Kopieren',
    'chat.thinking2': 'Denkt nach...',
    'chat.researching': 'Der Schiedsrichter recherchiert...',
    'chat.placeholder2': 'Frage den Schiedsrichter...',
    'chat.updating': 'Aktualisiert...',
    'admin.upload': 'Regeln hochladen',
    'admin.uploadTitle': 'Neue Regeln hochladen',
    'admin.uploadDesc': 'Lade eine Text- oder PDF-Datei mit den neuen Regeln hoch. Die KI wird sie sofort lernen.',
    'admin.uploadPick': 'Klicke zum Auswählen einer Datei',
    'admin.uploading': 'Hochladen und verarbeiten...',
    'admin.cancel': 'Abbrechen',
    'admin.corrections': 'Schiedsrichter-Korrekturen',
    'admin.correctionsPlaceholder': 'Eine Korrektur pro Zeile, z.B.: Mission 05 - die richtige Punktzahl ist 25 Punkte, weil...',
    'admin.saveCorrections': 'Korrekturen speichern',
    'admin.saved': 'Gespeichert',
    'season.label': 'Saison:',
    'auth.logout': 'Abmelden',
    'auth.login': 'Anmelden',
    'auth.logoutConfirmTitle': 'Abmelden',
    'auth.logoutConfirmMsg': 'Bist du sicher, dass du dich abmelden möchtest?',
    'auth.logoutConfirmYes': 'Ja, abmelden',
    'auth.logoutConfirmNo': 'Abbrechen',
    'auth.loginTitle': 'Anmelden',
    'auth.loginDesc': 'Um die KI zu nutzen, melde dich mit E-Mail an',
    'auth.loginWithEmail': 'Mit E-Mail anmelden',
    'auth.back': 'Zurück ↩',
    'intro.title': 'Willkommen beim Virtuellen Schiedsrichter',
    'intro.desc': 'KI-gestützter FLL-Schiedsrichter',
    'intro.subtitle': 'Virtueller Spielfeld-Schiedsrichter',
    'intro.descFull': 'Stelle jede Frage zu den Spielregeln — erhalte sofort den exakten Abschnitt aus dem Regelbuch und den Verweis auf offizielle Updates. Ein Community-Tool, ehrenamtlich vom Team Boeing 727 für die FLL-Community gebaut — kein offizielles FIRST-Produkt.',
    'intro.feature1Title': 'Spielregeln-Anfrage',
    'intro.feature1Desc': 'Sofortige Antwort mit dem exakten Abschnitt aus dem Regelbuch — ohne Raten.',
    'intro.feature2Title': 'Punkte erklärt',
    'intro.feature2Desc': 'Wie viele Punkte jede Mission wert ist und die genauen Abschlussbedingungen.',
    'intro.disclaimer': '⚠️ Wichtig:',
    'intro.disclaimerDesc': 'Der Virtuelle Schiedsrichter kann Fehler machen oder bestimmte Details verpassen. Je mehr Updates und Verbesserungen kommen, desto genauer und zuverlässiger werden die Antworten. Dies ist Teil der Entwicklung des Systems. Die Entscheidungen der Hauptschiedsrichter und der Zonenschiedsrichter bei der offiziellen Meisterschaft sind in jedem Fall immer maßgeblich und endgültig. Die Antworten des Bots dürfen während des Wettbewerbs nicht als verbindliche offizielle Bestätigung angesehen werden.',
    'intro.continue': 'Zur App fortfahren',
    'intro.continueLogin': 'Zur Anmeldung fortfahren',
    'intro.start': 'Starten',
    'intro.badge': 'Community-Tool von Boeing 727 • Für die FLL-Community',
    'intro.feature3Title': 'Schiedsrichter-Updates',
    'intro.feature3Desc': 'Klarstellungen, Entscheidungen und Änderungen der Saison — an einem Ort.',
    'intro.notOfficial': 'Community-Tool — kein offizielles FIRST-Produkt',
    'disclaimerPopup.title': 'Hinweis vor dem Eintritt ⚠️',
    'disclaimerPopup.body': 'Der Virtuelle Schiedsrichter ist eine schlaue KI, die helfen will, kann aber Fehler machen — wie wir alle.\n\nEr entscheidet nicht, was im Wettbewerb richtig ist. Im echten Wettbewerb entscheiden nur die menschlichen Feldschiedsrichter, und was sie sagen, ist immer endgültig.\n\nIm Zweifel immer einen echten Feldschiedsrichter fragen.',
    'disclaimerPopup.confirm': 'Gelesen und verstanden — Zum Schiedsrichter'
  },
  ru: {
    'app.title': 'Виртуальный судья',
    'app.titleEn': 'Виртуальный судья',
    'chat.thinking': 'Виртуальный судья думает...',
    'chat.placeholder': 'Задайте вопрос о правилах FLL...',
    'chat.send': 'Отправить',
    'chat.greeting': 'Привет! Я Виртуальный судья. Я знаю правила сезона {season}. Чем могу помочь?',
    'chat.systemHint': '(Инструкция судьи: Если вопрос касается новой миссии или новой ситуации - игнорируйте ранее обсуждённую миссию и не смешивайте правила или подсчёт очков разных миссий.)',
    'chat.commError': 'Ошибка связи. Пожалуйста, попробуйте снова.',
    'chat.connectionLost': 'Связь потеряна. Попробуйте позже.',
    'chat.suggestion1': 'Может ли робот расширяться?',
    'chat.suggestion2': 'Сколько очков за миссию 1?',
    'chat.suggestion3': 'Какое наказание за касание робота?',
    'chat.suggestion4': 'Правила зоны запуска',
    'chat.refereeTag': '📋 Виртуальный судья',
    'chat.foulTag': '🚨 Карточка фола судьи',
    'chat.copied': 'Ответ скопирован!',
    'chat.copy': 'Копировать',
    'chat.thinking2': 'Думает...',
    'chat.researching': 'Судья ищет...',
    'chat.placeholder2': 'Спросите судью...',
    'chat.updating': 'Обновление...',
    'admin.upload': 'Загрузить правила',
    'admin.uploadTitle': 'Загрузить новые правила',
    'admin.uploadDesc': 'Загрузите текстовый или PDF-файл с новыми правилами. ИИ изучит их немедленно.',
    'admin.uploadPick': 'Нажмите для выбора файла',
    'admin.uploading': 'Загрузка и обработка...',
    'admin.cancel': 'Отмена',
    'admin.corrections': 'Исправления судьи',
    'admin.correctionsPlaceholder': 'Одно исправление на строку, напр.: Миссия 05 - правильный счёт 25 очков, потому что...',
    'admin.saveCorrections': 'Сохранить исправления',
    'admin.saved': 'Сохранено',
    'season.label': 'Сезон:',
    'auth.logout': 'Выйти',
    'auth.login': 'Войти',
    'auth.logoutConfirmTitle': 'Выход',
    'auth.logoutConfirmMsg': 'Вы уверены, что хотите выйти?',
    'auth.logoutConfirmYes': 'Да, выйти',
    'auth.logoutConfirmNo': 'Отмена',
    'auth.loginTitle': 'Вход',
    'auth.loginDesc': 'Для использования ИИ войдите с email',
    'auth.loginWithEmail': 'Войти с Email',
    'auth.back': 'Назад ↩',
    'intro.title': 'Добро пожаловать к Виртуальному судье',
    'intro.desc': 'Судья FLL на базе ИИ',
    'intro.subtitle': 'Виртуальный судья поля',
    'intro.descFull': 'Задайте любой вопрос о правилах — получите мгновенный ответ с точным разделом из книги правил и ссылкой на официальные обновления. Общественный инструмент, созданный волонтёрами команды Boeing 727 для сообщества FLL — не официальный продукт FIRST.',
    'intro.feature1Title': 'Запрос правил игры',
    'intro.feature1Desc': 'Мгновенный ответ с точным разделом из книги правил — без догадок.',
    'intro.feature2Title': 'Подсчёт очков',
    'intro.feature2Desc': 'Сколько очков стоит каждая миссия и точные условия выполнения.',
    'intro.disclaimer': '⚠️ Важно:',
    'intro.disclaimerDesc': 'Виртуальный судья может допускать ошибки или упускать детали. По мере поступления обновлений и улучшений ответы станут более точными и надёжными. Это часть развития системы. Решения главных судей и судей зоны на официальных соревнованиях всегда являются определяющими и окончательными в любом случае. Ответы бота нельзя рассматривать как официальное обязательное подтверждение во время соревнований.',
    'intro.continue': 'Перейти к приложению',
    'intro.continueLogin': 'Перейти к входу',
    'intro.start': 'Начать запрос',
    'intro.badge': 'Инструмент сообщества от Boeing 727 • Для сообщества FLL',
    'intro.feature3Title': 'Обновления судьи',
    'intro.feature3Desc': 'Разъяснения, решения и изменения сезона — в одном месте.',
    'intro.notOfficial': 'Инструмент сообщества — не официальный продукт FIRST',
    'disclaimerPopup.title': 'Внимание перед входом ⚠️',
    'disclaimerPopup.body': 'Виртуальный судья — умный ИИ, который старается помочь, но может ошибаться — как и мы все.\n\nОн не решает, что правильно на соревновании. На настоящем соревновании решают только живые судьи зоны, и их слово — всегда окончательное.\n\nЕсли сомневаетесь, всегда спрашивайте настоящего судью зоны.',
    'disclaimerPopup.confirm': 'Прочитал и понял — Войти к судье'
  },
  pt: {
    'app.title': 'Juiz Virtual',
    'app.titleEn': 'Juiz Virtual',
    'chat.thinking': 'O juiz virtual está pensando...',
    'chat.placeholder': 'Faça uma pergunta sobre as regras da FLL...',
    'chat.send': 'Enviar',
    'chat.greeting': 'Olá! Sou o Juiz Virtual. Conheço as regras da temporada {season}. Como posso ajudar?',
    'chat.systemHint': '(Instrução do juiz: Se a pergunta for sobre uma nova missão ou nova situação - ignore a missão discutida anteriormente e não misture regras ou pontuações de missões diferentes.)',
    'chat.commError': 'Erro de comunicação. Por favor, tente novamente.',
    'chat.connectionLost': 'Conexão perdida. Tente novamente mais tarde.',
    'chat.suggestion1': 'Um robô pode se expandir?',
    'chat.suggestion2': 'Quantos pontos vale a missão 1?',
    'chat.suggestion3': 'Qual é a penalidade por tocar no robô?',
    'chat.suggestion4': 'Regras da zona de lançamento',
    'chat.refereeTag': '📋 Juiz Virtual',
    'chat.foulTag': '🚨 Cartão de Falta do Juiz',
    'chat.copied': 'Resposta copiada!',
    'chat.copy': 'Copiar',
    'chat.thinking2': 'Pensando...',
    'chat.researching': 'O juiz pesquisando...',
    'chat.placeholder2': 'Pergunte ao juiz...',
    'chat.updating': 'Atualizando...',
    'admin.upload': 'Enviar regras',
    'admin.uploadTitle': 'Enviar novas regras',
    'admin.uploadDesc': 'Envie um arquivo de texto ou PDF com as novas regras. A IA aprenderá imediatamente.',
    'admin.uploadPick': 'Clique para selecionar arquivo',
    'admin.uploading': 'Enviando e processando...',
    'admin.cancel': 'Cancelar',
    'admin.corrections': 'Correções do árbitro',
    'admin.correctionsPlaceholder': 'Uma correção por linha, ex.: Missão 05 - a pontuação correta é 25 pontos porque...',
    'admin.saveCorrections': 'Salvar correções',
    'admin.saved': 'Salvo',
    'season.label': 'Temporada:',
    'auth.logout': 'Sair',
    'auth.login': 'Entrar',
    'auth.logoutConfirmTitle': 'Sair',
    'auth.logoutConfirmMsg': 'Tem certeza de que deseja sair?',
    'auth.logoutConfirmYes': 'Sim, sair',
    'auth.logoutConfirmNo': 'Cancelar',
    'auth.loginTitle': 'Entrar',
    'auth.loginDesc': 'Para usar a IA, faça login com email',
    'auth.loginWithEmail': 'Entrar com Email',
    'auth.back': 'Voltar ↩',
    'intro.title': 'Bem-vindo ao Juiz Virtual',
    'intro.desc': 'Juiz FLL com IA',
    'intro.subtitle': 'Juiz de Campo Virtual',
    'intro.descFull': 'Faça qualquer pergunta sobre as regras — receba instantaneamente a seção exata do livro de regras e a referência às atualizações oficiais. Ferramenta comunitária criada voluntariamente pela equipe Boeing 727 para a comunidade FLL — não é um produto oficial da FIRST.',
    'intro.feature1Title': 'Consulta de Regras do Jogo',
    'intro.feature1Desc': 'Resposta instantânea com a seção exata do livro de regras — sem achismos.',
    'intro.feature2Title': 'Pontuação explicada',
    'intro.feature2Desc': 'Quantos pontos vale cada missão e as condições exatas de conclusão.',
    'intro.disclaimer': '⚠️ Importante:',
    'intro.disclaimerDesc': 'O Juiz Virtual pode cometer erros ou perder certos detalhes. À medida que atualizações e melhorias chegarem, as respostas serão mais precisas e confiáveis. Isso faz parte da evolução do sistema. As decisões dos árbitros principais e dos árbitros de zona na competição oficial são sempre decisivas e definitivas em qualquer caso. As respostas do bot não devem ser consideradas uma aprovação oficial vinculativa durante a competição.',
    'intro.continue': 'Continuar para o App',
    'intro.continueLogin': 'Continuar para o Login',
    'intro.start': 'Iniciar consulta',
    'intro.badge': 'Ferramenta comunitária da Boeing 727 • Para a comunidade FLL',
    'intro.feature3Title': 'Atualizações do árbitro',
    'intro.feature3Desc': 'Esclarecimentos, decisões e alterações da temporada — em um só lugar.',
    'intro.notOfficial': 'Ferramenta comunitária — não é um produto oficial da FIRST',
    'disclaimerPopup.title': 'Aviso antes de entrar ⚠️',
    'disclaimerPopup.body': 'O Juiz Virtual é uma IA inteligente que tenta ajudar, mas pode cometer erros — como todos nós.\n\nEle não decide o que é correto na competição. Na competição real apenas os juízes humanos da arena decidem, e o que eles dizem é sempre final.\n\nEm caso de dúvida, pergunte sempre a um juiz real da arena.',
    'disclaimerPopup.confirm': 'Li e entendi — Entrar no Juiz'
  },
  it: {
    'app.title': 'Arbitro Virtuale',
    'app.titleEn': 'Arbitro Virtuale',
    'chat.thinking': 'L\'arbitro virtuale sta pensando...',
    'chat.placeholder': 'Fai una domanda sulle regole FLL...',
    'chat.send': 'Invia',
    'chat.greeting': 'Ciao! Sono l\'Arbitro Virtuale. Conosco le regole della stagione {season}. Come posso aiutarti?',
    'chat.systemHint': '(Istruzione dell\'arbitro: Se la domanda riguarda una nuova missione o una nuova situazione - ignora la missione discussa in precedenza e non mescolare regole o punteggi di missioni diverse.)',
    'chat.commError': 'Errore di comunicazione. Per favore riprova.',
    'chat.connectionLost': 'Connessione persa. Riprova più tardi.',
    'chat.suggestion1': 'Un robot può espandersi?',
    'chat.suggestion2': 'Quanti punti vale la missione 1?',
    'chat.suggestion3': 'Qual è la penalità per toccare il robot?',
    'chat.suggestion4': 'Regole della zona di lancio',
    'chat.refereeTag': '📋 Arbitro Virtuale',
    'chat.foulTag': '🚨 Cartellino di Fallo dell\'Arbitro',
    'chat.copied': 'Risposta copiata!',
    'chat.copy': 'Copia',
    'chat.thinking2': 'Pensando...',
    'chat.researching': 'L\'arbitro sta cercando...',
    'chat.placeholder2': 'Chiedi all\'arbitro...',
    'chat.updating': 'Aggiornamento...',
    'admin.upload': 'Carica regole',
    'admin.uploadTitle': 'Carica nuove regole',
    'admin.uploadDesc': 'Carica un file di testo o PDF con le nuove regole. L\'IA le imparerà immediatamente.',
    'admin.uploadPick': 'Clicca per selezionare il file',
    'admin.uploading': 'Caricamento e elaborazione...',
    'admin.cancel': 'Annulla',
    'admin.corrections': 'Correzioni arbitro',
    'admin.correctionsPlaceholder': 'Una correzione per riga, es.: Missione 05 - il punteggio corretto è 25 punti perché...',
    'admin.saveCorrections': 'Salva correzioni',
    'admin.saved': 'Salvato',
    'season.label': 'Stagione:',
    'auth.logout': 'Esci',
    'auth.login': 'Accedi',
    'auth.logoutConfirmTitle': 'Esci',
    'auth.logoutConfirmMsg': 'Sei sicuro di voler uscire?',
    'auth.logoutConfirmYes': 'Sì, esci',
    'auth.logoutConfirmNo': 'Annulla',
    'auth.loginTitle': 'Accedi',
    'auth.loginDesc': 'Per usare l\'IA, accedi con email',
    'auth.loginWithEmail': 'Accedi con Email',
    'auth.back': 'Indietro ↩',
    'intro.title': 'Benvenuto all\'Arbitro Virtuale',
    'intro.desc': 'Arbitro FLL basato su IA',
    'intro.subtitle': 'Arbitro di Campo Virtuale',
    'intro.descFull': 'Fai qualsiasi domanda sulle regole — ottieni subito la sezione esatta del regolamento e il riferimento agli aggiornamenti ufficiali. Strumento comunitario creato volontariamente dal team Boeing 727 per la comunità FLL — non è un prodotto ufficiale FIRST.',
    'intro.feature1Title': 'Richiesta Regole del Gioco',
    'intro.feature1Desc': 'Risposta immediata con la sezione esatta del regolamento — senza supposizioni.',
    'intro.feature2Title': 'Punteggio spiegato',
    'intro.feature2Desc': 'Quanti punti vale ogni missione e le condizioni esatte di completamento.',
    'intro.disclaimer': '⚠️ Importante:',
    'intro.disclaimerDesc': 'L\'Arbitro Virtuale potrebbe commettere errori o mancare certi dettagli. Man mano che arrivano aggiornamenti e miglioramenti, le risposte diventeranno più accurate e affidabili. Questa fa parte dell\'evoluzione del sistema. Le decisioni degli arbitri capo e degli arbitri di zona nella competizione ufficiale sono sempre decisive e definitive in ogni caso. Le risposte del bot non devono essere considerate un\'approvazione ufficiale vincolante durante la competizione.',
    'intro.continue': 'Continua all\'App',
    'intro.continueLogin': 'Continua al Login',
    'intro.start': 'Inizia',
    'intro.badge': 'Strumento comunitario di Boeing 727 • Per la comunità FLL',
    'intro.feature3Title': 'Aggiornamenti arbitro',
    'intro.feature3Desc': 'Chiarimenti, decisioni e modifiche della stagione — in un unico posto.',
    'intro.notOfficial': 'Strumento comunitario — non è un prodotto ufficiale FIRST',
    'disclaimerPopup.title': 'Avviso prima di entrare ⚠️',
    'disclaimerPopup.body': 'L\'Arbitro Virtuale è un\'IA intelligente che cerca di aiutare, ma può sbagliare — come tutti noi.\n\nNon decide cosa è corretto in gara. Nella gara reale decidono solo gli arbitri umani dell\'arena, e ciò che dicono è sempre definitivo.\n\nIn caso di dubbio, chiedi sempre a un vero arbitro dell\'arena.',
    'disclaimerPopup.confirm': 'Ho letto e compreso — Entra nell\'Arbitro'
  },
  zh: {
    'app.title': '虚拟裁判',
    'app.titleEn': '虚拟裁判',
    'chat.thinking': '虚拟裁判正在思考...',
    'chat.placeholder': '提出关于FLL规则的问题...',
    'chat.send': '发送',
    'chat.greeting': '你好！我是虚拟裁判。我了解{season}赛季的规则。有什么可以帮你的？',
    'chat.systemHint': '(裁判指示：如果问题涉及新任务或新情况 - 忽略之前讨论的任务，不要混淆不同任务的规则或得分。)',
    'chat.commError': '通信错误。请重试。',
    'chat.connectionLost': '连接丢失。请稍后再试。',
    'chat.suggestion1': '机器人可以扩展吗？',
    'chat.suggestion2': '任务1的得分是多少？',
    'chat.suggestion3': '触碰机器人的处罚是什么？',
    'chat.suggestion4': '发射区规则',
    'chat.refereeTag': '📋 虚拟裁判',
    'chat.foulTag': '🚨 裁判犯规卡',
    'chat.copied': '答案已复制！',
    'chat.copy': '复制',
    'chat.thinking2': '思考中...',
    'chat.researching': '裁判正在研究...',
    'chat.placeholder2': '问裁判...',
    'chat.updating': '更新中...',
    'admin.upload': '上传规则',
    'admin.uploadTitle': '上传新规则',
    'admin.uploadDesc': '上传包含新规则的文本或PDF文件。AI将立即学习。',
    'admin.uploadPick': '点击选择文件',
    'admin.uploading': '上传和处理中...',
    'admin.cancel': '取消',
    'admin.corrections': '裁判修正',
    'admin.correctionsPlaceholder': '每行一个修正，例如：任务05 - 正确得分是25分，因为……',
    'admin.saveCorrections': '保存修正',
    'admin.saved': '已保存',
    'season.label': '赛季:',
    'auth.logout': '退出',
    'auth.login': '登录',
    'auth.logoutConfirmTitle': '退出',
    'auth.logoutConfirmMsg': '您确定要退出吗？',
    'auth.logoutConfirmYes': '是的，退出',
    'auth.logoutConfirmNo': '取消',
    'auth.loginTitle': '登录',
    'auth.loginDesc': '要使用AI，请用邮箱登录',
    'auth.loginWithEmail': '用邮箱登录',
    'auth.back': '返回 ↩',
    'intro.title': '欢迎使用虚拟裁判',
    'intro.desc': '基于AI的FLL裁判',
    'intro.subtitle': '虚拟场地裁判',
    'intro.descFull': '询问任何关于比赛规则的问题 — 立即获得规则手册中的准确章节和官方更新的引用。这是由Boeing 727团队为FLL社区志愿构建的社区工具 — 非FIRST官方产品。',
    'intro.feature1Title': '游戏规则查询',
    'intro.feature1Desc': '即时回答并引用规则手册中的准确章节 — 无需猜测。',
    'intro.feature2Title': '得分详解',
    'intro.feature2Desc': '每个任务值多少分以及完成的确切条件。',
    'intro.disclaimer': '⚠️ 重要：',
    'intro.disclaimerDesc': '虚拟裁判可能会犯错或遗漏某些细节。随着更新和改进的到来，答案将变得更加准确和可靠。这是系统发展的一部分。在正式比赛中，主裁判和赛区裁判的判罚在任何情况下始终是决定性的和最终的。比赛期间，不得将机器人的回答视为具有约束力的官方批准。',
    'intro.continue': '继续进入应用',
    'intro.continueLogin': '继续登录',
    'intro.start': '开始查询',
    'intro.badge': 'Boeing 727 社区工具 • 献给FLL社区',
    'intro.feature3Title': '裁判更新',
    'intro.feature3Desc': '赛季中发布的澄清、裁决和变更 — 尽在一处。',
    'intro.notOfficial': '社区工具 — 非FIRST官方产品',
    'disclaimerPopup.title': '进入前请注意 ⚠️',
    'disclaimerPopup.body': '虚拟裁判是一个试图帮助你的智能AI，但它也会犯错——就像我们有时也会困惑一样。\n\n它不能决定比赛中什么是正确的。在真正的比赛中，只有现场的人类裁判才能决定，他们说的永远是最终结果。\n\n如有疑问，请务必询问真正的现场裁判。',
    'disclaimerPopup.confirm': '我已阅读并理解 — 进入裁判'
  },
  ja: {
    'app.title': 'バーチャル審判',
    'app.titleEn': 'バーチャル審判',
    'chat.thinking': 'バーチャル審判が考えています...',
    'chat.placeholder': 'FLLルールについて質問する...',
    'chat.send': '送信',
    'chat.greeting': 'こんにちは！バーチャル審判です。{season}シーズンのルールを知っています。どのようにお手伝いできますか？',
    'chat.systemHint': '(審判の指示：質問が新しいミッションや新しい状況に関するものである場合 - 以前に議論されたミッションは無視し、異なるミッションのルールやスコアを混ぜないでください。)',
    'chat.commError': '通信エラー。もう一度お試しください。',
    'chat.connectionLost': '接続が失われました。後でもう一度お試しください。',
    'chat.suggestion1': 'ロボットは拡張できますか？',
    'chat.suggestion2': 'ミッション1のスコアは？',
    'chat.suggestion3': 'ロボットに触れた場合のペナルティは？',
    'chat.suggestion4': '発射ゾーンのルール',
    'chat.refereeTag': '📋 バーチャル審判',
    'chat.foulTag': '🚨 審判フォールカード',
    'chat.copied': '回答をコピーしました！',
    'chat.copy': 'コピー',
    'chat.thinking2': '考え中...',
    'chat.researching': '審判が調査中...',
    'chat.placeholder2': '審判に質問...',
    'chat.updating': '更新中...',
    'admin.upload': 'ルールをアップロード',
    'admin.uploadTitle': '新しいルールをアップロード',
    'admin.uploadDesc': '新しいルールを含むテキストまたはPDFファイルをアップロード。AIがすぐに学習します。',
    'admin.uploadPick': 'クリックしてファイルを選択',
    'admin.uploading': 'アップロードと処理中...',
    'admin.cancel': 'キャンセル',
    'admin.corrections': '審判修正',
    'admin.correctionsPlaceholder': '1行に1つの修正。例:ミッション05 - 正しい得点は25点、なぜなら...',
    'admin.saveCorrections': '修正を保存',
    'admin.saved': '保存しました',
    'season.label': 'シーズン:',
    'auth.logout': 'ログアウト',
    'auth.login': 'ログイン',
    'auth.logoutConfirmTitle': 'ログアウト',
    'auth.logoutConfirmMsg': 'ログアウトしてもよろしいですか？',
    'auth.logoutConfirmYes': 'はい、ログアウト',
    'auth.logoutConfirmNo': 'キャンセル',
    'auth.loginTitle': 'ログイン',
    'auth.loginDesc': 'AIを使用するには、メールでログインしてください',
    'auth.loginWithEmail': 'メールでログイン',
    'auth.back': '戻る ↩',
    'intro.title': 'バーチャル審判へようこそ',
    'intro.desc': 'AI搭載FLL審判',
    'intro.subtitle': 'バーチャルフィールド審判',
    'intro.descFull': 'ルールについて何でも質問 — ルールブックの正確な条項と公式アップデートへの参照を即座に取得。Boeing 727チームがFLLコミュニティのためにボランティアで構築したコミュニティツール — FIRST公式製品ではありません。',
    'intro.feature1Title': 'ゲームルールの照会',
    'intro.feature1Desc': 'ルールブックの正確な条項付きで即答 — 推測なし。',
    'intro.feature2Title': '得点解説',
    'intro.feature2Desc': '各ミッションの配点と達成の正確な条件。',
    'intro.disclaimer': '⚠️ 重要：',
    'intro.disclaimerDesc': 'バーチャル審判は誤りを犯したり、 certainな詳細を見逃すことがあります。更新と改善が届くにつれて、回答はより正確で信頼性が高くなります。これはシステムの進化の一部です。公式大会における主審およびゾーン審判の判定は、いかなる場合でも常に決定的かつ最終的なものです。競技中、ボットの回答を公式の拘束力のある承認と見なしてはなりません。',
    'intro.continue': 'アプリに進む',
    'intro.continueLogin': 'ログインに進む',
    'intro.start': '開始',
    'intro.badge': 'Boeing 727 コミュニティツール • FLLコミュニティのために',
    'intro.feature3Title': '審判アップデート',
    'intro.feature3Desc': 'シーズン中に公開された澄清、裁定、変更 — 一箇所に。',
    'intro.notOfficial': 'コミュニティツール — FIRST公式製品ではありません',
    'disclaimerPopup.title': '入る前の注意 ⚠️',
    'disclaimerPopup.body': 'バーチャル審判はルールを理解するのを手伝おうとする賢いAIですが、時々間違えることがあります — 私たちも混乱するように。\n\nそれは競技で何が正しいかを決定しません。本当の競技では、現場の人間の審判だけが決定し、彼らの言葉が常に最終決定です。\n\n疑問がある場合は、必ず本物の現場審判に聞いてください。',
    'disclaimerPopup.confirm': '読んで理解しました — 審判に入る'
  },
  ko: {
    'app.title': '가상 심판',
    'app.titleEn': '가상 심판',
    'chat.thinking': '가상 심판이 생각하고 있습니다...',
    'chat.placeholder': 'FLL 규칙에 대해 질문하기...',
    'chat.send': '전송',
    'chat.greeting': '안녕하세요! 가상 심판입니다. {season} 시즌 규칙을 알고 있습니다. 어떻게 도와드릴까요?',
    'chat.systemHint': '(심판 지침: 질문이 새로운 미션이나 새로운 상황에 관한 경우 - 이전에 논의된 미션은 무시하고 다른 미션의 규칙이나 점수를 혼동하지 마세요.)',
    'chat.commError': '통신 오류입니다. 다시 시도해 주세요.',
    'chat.connectionLost': '연결이 끊어졌습니다. 나중에 다시 시도해 주세요.',
    'chat.suggestion1': '로봇이 확장될 수 있나요?',
    'chat.suggestion2': '미션 1의 점수는?',
    'chat.suggestion3': '로봇을 만졌을 때의 페널티는?',
    'chat.suggestion4': '발사 존 규칙',
    'chat.refereeTag': '📋 가상 심판',
    'chat.foulTag': '🚨 심판 반칙 카드',
    'chat.copied': '답변이 복사되었습니다!',
    'chat.copy': '복사',
    'chat.thinking2': '생각 중...',
    'chat.researching': '심판이 조사 중...',
    'chat.placeholder2': '심판에게 질문...',
    'chat.updating': '업데이트 중...',
    'admin.upload': '규칙 업로드',
    'admin.uploadTitle': '새 규칙 업로드',
    'admin.uploadDesc': '새 규칙이 포함된 텍스트 또는 PDF 파일을 업로드하세요. AI가 즉시 학습합니다.',
    'admin.uploadPick': '파일 선택을 위해 클릭',
    'admin.uploading': '업로드 및 처리 중...',
    'admin.cancel': '취소',
    'admin.corrections': '심판 수정',
    'admin.correctionsPlaceholder': '한 줄에 하나의 수정, 예: 미션 05 - 정확한 점수는 25점입니다. 왜냐하면...',
    'admin.saveCorrections': '수정 저장',
    'admin.saved': '저장됨',
    'season.label': '시즌:',
    'auth.logout': '로그아웃',
    'auth.login': '로그인',
    'auth.logoutConfirmTitle': '로그아웃',
    'auth.logoutConfirmMsg': '정말 로그아웃하시겠습니까?',
    'auth.logoutConfirmYes': '예, 로그아웃',
    'auth.logoutConfirmNo': '취소',
    'auth.loginTitle': '로그인',
    'auth.loginDesc': 'AI를 사용하려면 이메일로 로그인하세요',
    'auth.loginWithEmail': '이메일로 로그인',
    'auth.back': '뒤로 ↩',
    'intro.title': '가상 심판에 오신 것을 환영합니다',
    'intro.desc': 'AI 기반 FLL 심판',
    'intro.subtitle': '가상 필드 심판',
    'intro.descFull': '경기 규칙에 대해 무엇이든 질문하세요 — 규칙집의 정확한 조항과 공식 업데이트 참조를 즉시 받아보세요. Boeing 727 팀이 FLL 커뮤니티를 위해 자발적으로 구축한 커뮤니티 도구 — 공식 FIRST 제품이 아닙니다.',
    'intro.feature1Title': '게임 규칙 문의',
    'intro.feature1Desc': '규칙집의 정확한 조항과 함께 즉시 답변 — 추측 없음.',
    'intro.feature2Title': '점수 설명',
    'intro.feature2Desc': '각 미션의 배점과 완료를 위한 정확한 조건.',
    'intro.disclaimer': '⚠️ 중요:',
    'intro.disclaimerDesc': '가상 심판은 실수를 하거나 특정 세부 사항을 놓칠 수 있습니다. 업데이트와 개선이 올수록 답변은 더 정확하고 신뢰할 수 있게 됩니다. 이는 시스템 진화의 일부입니다. 공식 대회에서 주심과 존 심판의 판정은 어떤 경우에도 항상 결정적이고 최종적입니다. 대회 중 봇의 답변을 공식적인 구속력 있는 승인으로 간주해서는 안 됩니다.',
    'intro.continue': '앱으로 계속',
    'intro.continueLogin': '로그인으로 계속',
    'intro.start': '시작',
    'intro.badge': 'Boeing 727 커뮤니티 도구 • FLL 커뮤니티를 위해',
    'intro.feature3Title': '심판 업데이트',
    'intro.feature3Desc': '시즌 동안 게시된 설명, 판정 및 변경 사항 — 한 곳에서.',
    'intro.notOfficial': '커뮤니티 도구 — 공식 FIRST 제품이 아닙니다',
    'disclaimerPopup.title': '입장 전 주의 ⚠️',
    'disclaimerPopup.body': '가상 심판은 규칙을 이해하도록 돕는 똑똑한 AI이지만, 우리처럼 가끔 실수할 수 있습니다.\n\n그것은 대회에서 무엇이 옳은지 결정하지 않습니다. 실제 대회에서는 현장의 인간 심판만이 결정하며, 그들이 말하는 것이 항상 최종입니다.\n\n의심스러우면 항상 실제 현장 심판에게 물어보세요.',
    'disclaimerPopup.confirm': '읽고 이해했습니다 — 심판으로 입장'
  },
};

const rtlLanguages: LanguageCode[] = ['he', 'ar'];

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  t: (key: string) => string;
  currentLang: Language;
  languages: Language[];
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    return (localStorage.getItem('app_language') as LanguageCode) || 'he';
  });

  const setLanguage = (code: LanguageCode) => {
    setLanguageState(code);
    localStorage.setItem('app_language', code);
    document.documentElement.lang = code;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const lang = language as LanguageCode;
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  const currentLang = languages.find(l => l.code === language) || languages[0];
  const isRTL = rtlLanguages.includes(language);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLang, languages, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}